name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch (optional)

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/unity-action@v2
      with:
        version: '6000.0.31f1'  # Specify the Unity version you are using
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build WebGL
      run: |
        ./unity -batchmode -nographics -silent-crashes -logFile build.log -projectPath . -executeMethod WebGLBuild.BuildWebGL

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: webgl-build
        path: Build/WebGL

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job is completed first
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: webgl-build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.1.0
      with:
        branch: gh-pages  # Deploy to the gh-pages branch
        folder: Build/WebGL  # The folder that contains the WebGL build
        token: ${{ secrets.GITHUB_TOKEN }}
